name: test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg-version: [ "9.1", "9.5", "9.6", "10", "11", "12", "13", "14", "15", "16", "17" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --file docker/Dockerfile --tag "pgxtest:${{ matrix.pg-version }}" --build-arg "PGVERSION=${{ matrix.pg-version }}"

      - name: Test
        run: docker run --rm -v `pwd`:/workspace "pgxtest:${{ matrix.pg-version }}" /test.sh
